
services:
  postgres:
    image: postgres:15
    env_file: .env.dev
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d blogdb']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - '8001:5540'               # Проброс порта 5540 из контейнера на 8001 хоста
    volumes:
      - redisinsight_data:/db    # Для сохранения данных RedisInsight
    environment:
      - REDISINSIGHT_HOST=0.0.0.0 # Чтобы слушал на всех интерфейсах
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file: .env.dev
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025' # SMTP порт
      - '8025:8025' # Web интерфейс
    restart: unless-stopped
    networks:
      default:
        aliases:
          - mailhog

volumes:
  pgdata:
  minio_data:
  redisinsight_data:
