services:
  app:
    build:
      context: .
    env_file: .env.dev
    command: sh -c "npx prisma migrate deploy && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    env_file: .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

volumes:
  pgdata:
