services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - blog-network


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SERVER_ROOT_URL: "https://grafana.blogpsy.ru"
      GF_SERVER_SERVE_FROM_SUB_PATH: "false"
    ports:
      - "127.0.0.1:3001:3000"  # Только локальный доступ
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - blog-network


  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgress-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/blogdb?sslmode=disable"
    ports:
      - "127.0.0.1:9187:9187"
    restart: unless-stopped
    networks:
      - blog-network


networks:
  blog-network:
    external: true
    name: blog-network

volumes:
  prometheus_data:
  grafana_data:

