services:
  app:
    image: andnikdoc/api.blogpsy.ru:latest
    container_name: blog-app
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "0.0.0.0:5000:5000"
    networks:
      - blog-network
    depends_on:
      blog-postgres:
        condition: service_healthy
      blog-redis:
        condition: service_healthy

networks:
  blog-network:
    external: true
    name: blog-network
