services:
  app:
    image: andnikdoc/api.blogpsy.ru:${TAG}
    container_name: blog-app
    restart: unless-stopped
    env_file:
      - .env.prod
      - .env.tag

    ports:
      - "0.0.0.0:5000:5000"
      - "0.0.0.0:5555:5555"
    networks:
      - blog-network


networks:
  blog-network:
    external: true
    name: blog-network