services:
  migrator:
    image: andnikdoc/api.blogpsy.ru:latest
    container_name: api-migrator
    command: ["npx", "prisma", "migrate", "deploy"]
    restart: "on-failure"
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy

  app:
    image: andnikdoc/api.blogpsy.ru:latest
    container_name: api-blogpsy
    restart: unless-stopped
    ports:
      - "5000"
    env_file:
      - .env.prod
    depends_on:
      migrator:
        condition: service_completed_successfully
    networks:
      - backend

  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - backend

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./html:/usr/share/nginx/html
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./html:/data/acme-challenge
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata: