/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Main API
 * API для работы с пользователями, постами и комментариями
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAuthMe200User } from './getApiAuthMe200User';

export type GetApiAuthMe200 = {
  message?: string;
  user?: GetApiAuthMe200User;
};
