/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Main API
 * API для работы с пользователями, постами и комментариями
 * OpenAPI spec version: 1.0.0
 */

export type GetApiUserUserIdPostsParams = {
/**
 * Номер страницы
 */
page?: number;
/**
 * Количество записей на странице
 */
limit?: number;
};
