/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Main API
 * API для работы с пользователями, постами и комментариями
 * OpenAPI spec version: 1.0.0
 */

export interface PostCreate {
  /**
   * @minLength 3
   * @maxLength 100
   */
  title: string;
  /**
   * @minLength 10
   * @maxLength 5000
   */
  content: string;
}
