/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Main API
 * API для работы с пользователями, постами и комментариями
 * OpenAPI spec version: 1.0.0
 */

export type PutApiUserProfileBody = {
  /**
   * @minLength 2
   * @maxLength 50
   */
  name?: string;
  /** @maxLength 500 */
  bio?: string;
  website?: string;
};
