name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Rsync files
        uses: burnett01/rsync-deployments@5.2.3
        with:
          switches: -avzr --delete
          path: |
            Dockerfile
            docker-compose.prod.yml
            .env.prod
            dist/
            prisma/
            nginx/
          remote_path: ~/myapp/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
      
      - name: Restart Docker
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/myapp
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build