name: Production Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy files
        run: |
          scp -o StrictHostKeyChecking=no \
              Dockerfile docker-compose.prod.yml .env.prod \
              root@${{ secrets.SSH_HOST }}:/root/myapp/
          
          scp -r -o StrictHostKeyChecking=no \
              dist/ prisma/ nginx/ \
              root@${{ secrets.SSH_HOST }}:/root/myapp/

      - name: Restart services
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} << 'EOF'
          cd /root/myapp
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d --build
          docker system prune -af
          EOF